### ISSUE TITLE
Number is integer

### ISSUE THREAD

**Issue by jamierumbelow** [strongloop/loopback-connector-postgresql#100]
Is there a reason why the `number` data type casts to an `INTEGER`? I'd expect anything named number to let me use floats.

**Comment by raymondfeng** [comment]
You can customize it for properties. For example:
```json
"myProp": {
  "type": "Number",
  "postgresql": {
    "dataType": "NUMBER"
  }
}
```

**Comment by jamierumbelow** [comment]
Yep, that's all good, thanks. But how come the default is integer?

**Comment by phiat** [comment]
I had some luck with:

```
"myProp": {
  "type": "Number",
  "postgresql": {
    "dataType": "Numeric"
  }
}
```

**Comment by davidcheung** [comment]
I believe that's because the default datatype mapping of `number` would need to support `ID` fields. 

Trying to clean up issues so we keep only feature requests / bug reports on github, and discussion and questions on [Google groups](https://groups.google.com/forum/#!forum/loopbackjs)

Looks like the problem was solved, closing issue now, please reopen if you see fit, thanks!
