### ISSUE TITLE
Support for array type

### ISSUE THREAD

**Issue by alFReD-NSH** [strongloop/loopback-connector-postgresql#105]
Right if we make any type an array it will make it an `character varying(1024)`. For example arrays of integers should instead be `integer[]`. Here's the documentation for it: http://www.postgresql.org/docs/current/static/arrays.html

**Comment by jaulz** [comment]
+1

**Comment by Sogl** [comment]
+1

**Comment by ChopperLee2011** [comment]
i also want this feature to be implement, so try to add code here, not finish code yet, but works
https://github.com/ChopperLee2011/loopback-connector-postgresql/blob/master/lib/migration.js#L526

**Comment by xapou** [comment]
Same issue the other way round: when discovering the columns from the datasource : a String[] column is translated into a string in the model.

**Comment by digitalsadhu** [comment]
@superkhau how hard would this be to support? Looking through the source it's not obvious to me how/where I would go about trying to implement this. I'd be keen to put some time into this if someone was willing to give me some pointers.

**Comment by alFReD-NSH** [comment]
Actually this might conflict with the json type. It'll be nice to have both

**Comment by superkhau** [comment]
@digitalsadhu I'm not sure without digging deeper, but it should be similar to the GeoPoint implementation: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/geo.js. We definitely need a way for users to add custom datatypes in LB3.

>how hard would this be to support?

@raymondfeng Please chime in here as you have a much better idea with regards to the difficulty here.

**Comment by shaharz** [comment]
I have got a PoC working. There weren't that many changes but they're spread over three modules. The loopback-connector change in particular required an ugly hack due to the fact PostgreSQL requires different array notations in different situations (see [this ruby-pg issue discussion](https://bitbucket.org/ged/ruby-pg/issues/145/postgresql-statements-and-array-values) for details).

Anyway, these are the changes I had to make: https://gist.github.com/shaharz/2095dcc025ab142c20af17e6a9fd6b9a
I'd consider this pre-alpha and definitely not fit for production use without further testing.

It'd be great to see something like this integrated into Loopback.

**Comment by nidhhoggr** [comment]
Having a related issue trying to update/insert an values for integer array type. Is this supported yet in a newer version or will it ever be? My current version is ^2.3.0

**Comment by bvenkatr** [comment]
+1

**Comment by rizz360** [comment]
Why has this been closed? What is the recommend way of implementing arrays?
