### ISSUE TITLE
varchar(1024) is too short for JSON fieldtype

### ISSUE THREAD

**Issue by taras** [strongloop/loopback-connector-postgresql#122]
The default data length for an `Object` property is 1024 characters. 

This can become a problem in libraries that provide their own Loopback models - such as [loopback-component-passport](https://github.com/strongloop/loopback-component-passport) as can be seen from [this issue](https://github.com/strongloop/loopback-component-passport/issues/84). 

This component has a [userIdentity model with profile property of Object type](https://github.com/strongloop/loopback-component-passport/blob/master/lib/models/user-identity.json#L18). For GitHub and Google profiles, that default length is too short.

This raises 2 questions:
1. Can we use JSON Data Type when it's available which can handle up to [1GB of data](http://stackoverflow.com/questions/12632871/size-limit-of-json-data-type-in-postgresql)
2. Can we bump up the default rate to something bigger?

**Comment by davidcheung** [comment]
Cleaning up old issues, Thanks for bringing this up, I think this issue is out-of-date now 
Looks like this has been addressed, its now default as `TEXT`. https://github.com/strongloop/loopback-connector-postgresql/blob/ff75c74ece50b900f18ed4d027ac4ffa82728f02/lib/migration.js#L530

Closing issue now, please reopen if you see fit, thanks
