### ISSUE TITLE
SQL syntax identifiers

### ISSUE THREAD

**Issue by paulomcnally** [strongloop/loopback-connector-postgresql#24]
Hello.

I create tables into database using this code:
https://gist.github.com/paulomcnally/9eef6e3fa4f622a0dc67

On my custom models i define options.postgresql.table ([example](https://gist.github.com/paulomcnally/6d0b029beedd6605102f)).

Model name: **UserEventType**
Table name: **user_event_types**

If i don't define options.postgresql.table then my table name is: **usereventtype**

SQL syntax identifiers
http://www.postgresql.org/docs/current/interactive/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

## Bad
Model: User
Table: user

## Good
Model: User
Table: users

## Bad
Model: AccessToken
Table: accesstoken

## Good
Model: AccessToken
Table: access_token

The error is in the function [escapeName](https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/postgresql.js#L624) on this line of code: https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/postgresql.js#L640

**Comment by davidcheung** [comment]
Hi @paulomcnally, trying to clean up issues from long time ago, this function no longer exists I assume this issue is fixed now? the function I believe is replaced by [this blob](https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/postgresql.js#L326-L330) now as it handles it differently
```js
PostgreSQL.prototype.tableEscaped = function(model) {
  var schema = this.schema(model) || 'public';
  return this.escapeName(schema) + '.' +
    this.escapeName(this.table(model));
};
```
going to close this issue, please reopen if you see fit. Thanks
