### ISSUE TITLE
Connector does not support empty update

### ISSUE THREAD

**Issue by hvlawren** [strongloop/loopback-connector-postgresql#339]
# Description/Steps to reproduce
run patchAttributes on a model and provide an empty object as the payload, e.g. 

PATCH /api/users/1 {}

# Expected result

200 or 204, no error thrown

# Actual result

500 thrown, connector sends invalid SQL to the DB, e.g. 

`UPDATE "public"."assettype" SET  WHERE "id"=931;`

# Additional information

darwin x64 8.11.1

**Comment by hvlawren** [comment]
Both the Cloudant connector and the in memory connector allow for empty updates.

**Comment by aharbis** [comment]
Can we get any feedback on this?

**Comment by aharbis** [comment]
@dhmlau I do not believe this has been fixed. Any chance we can keep this open and investigate?

**Comment by dhmlau** [comment]
Sure. 
We recently added the support for PATCH, see PR https://github.com/strongloop/loopback-next/pull/3199, and our milestone blog: https://strongloop.com/strongblog/loopback-june-2019-milestone/.   Could you please verify if it's been fixed? Thanks! 

cc @bajtos

**Comment by bajtos** [comment]
Based on the report, it seems to me that the problem is in individual connectors that are not prepared to handle the case where the `patch` object contains no properties. Considering that this situation should be handled the same way by all connectors, I think it makes sense to detect empty patch payloads in `@loopback/repository` and/or `loopback-datasource-juggler`.

To ensure all connectors work consistently, we should add a test to [`packages/repository-tests`](https://github.com/strongloop/loopback-next/tree/master/packages/repository-tests) to verify.
