### ISSUE TITLE
Using multiple schemas getting error: relation "index_name" already exists

### ISSUE THREAD

**Issue by frzkhan** [strongloop/loopback-connector-postgresql#354]
I am using multiple schemas, 'public' for production and 'dev' for development in the same database
when I run a migration after modifying a few indexes, I get this error

`error: relation "index_name_idx" already exists`

this index does not exist on 'dev' schema but on 'public' while im using the 'dev' schema

after adding debug log `DEBUG=loopback:connector:* npm start`, i found out that drop index query does not have a schema name
`DROP INDEX "index_name_idx"`

It should be `DROP INDEX "schema_name"."index_name_idx"`

its a small fix if you guys can help out

thanks

**Comment by trzopekm** [comment]
I think the following problem is somehow connected to the topic of this issue. 
In case of using a schema different than `public`, when running `autoupdate`, an error occures `  loopback:connector:postgresql error: index "type_from_index" does not exist`
caused by following sql being executed:
```
DROP INDEX "type_from_index";
CREATE  INDEX "type_from_index" ON "tenant1"."migrationmap" ( "type" ASC, "from" ASC)
```
Drop part of this sql is created by line 599 in `migration.js` `sql.push('DROP INDEX ' + self.escapeName(indexName));`
Shouldn't it be: `sql.push('DROP INDEX ' + self.escapeName(indexName)) + 'IF EXISTS'`  ?

**Comment by jlawrencecfm** [comment]
I'm getting a different symptom from the same problem:
error: index "label_key_value_idx" does not exist

the following is the SQL that runs:
```sql
DROP INDEX "label_key_value_idx";
CREATE  INDEX "label_key_value_idx" ON "iot"."label" ( "key" ASC, "value" ASC)
```

Looks like the drop clause needs to indicate the 'ON' ?
