### ISSUE TITLE
Support with Loopback 4

### ISSUE THREAD

**Issue by gerahimanshu** [strongloop/loopback-connector-postgresql#393]
As per the Loopback 4 documentation:  https://loopback.io/doc/en/lb4/ 
Postgresql connector documentation is given with respect to the previous version of Loopback which lacks all the new features for creating models, repositories, controllers that has been recently introduced with Loopback 4
Can anyone help me in knowing how is Postgresql connector gonna work with Loopback 4.
I cannot find the given documentation for the same compatible with Loopback 4.

Thanks,
Himanshu Gera

**Comment by dhmlau** [comment]
@gerahimanshu, datasource in LoopBack 4 provides the configuration of the connectors. 
When creating a DataSource in LoopBack 4, you'll need to specify connector.  Example of how to do it can be found in: https://loopback.io/doc/en/lb4/todo-tutorial-datasource.html.  For the postgresql case, you'll specify the Postgresql connector instead of the in-memory connector in the given example.

Hope it helps.

**Comment by dhmlau** [comment]
@gerahimanshu, I believe we've answered your question. Closing as resolved. Thanks.
