### ISSUE TITLE
BigInt returned as string

### ISSUE THREAD

**Issue by vikramkh** [strongloop/loopback-connector-postgresql#403]
## Steps to reproduce

I have two models, Players and Team. Both ids are BigInts. Players has a foreign Key teamId which is of type BigInt in the database, and number in Postgres model properties. 

## Current Behavior

When I do .find() on players, teamId is returned as a string. If I do .execute, both id and teamId are returned as a string.

## Expected Behavior

When I do .find(), or .execute, both id and teamId should be returned as numbers (or both as strings for consistencies sake)

## Additional information

<!--
Copy+paste the output of these two commands:
 darwin x64 10.15.3
  @loopback/authentication@3.2.3
├── @loopback/authentication-passport@1.0.5
├── @loopback/boot@1.5.9
├── @loopback/build@2.0.14
├── @loopback/context@1.23.3
├── @loopback/core@1.10.5
├── @loopback/openapi-v3@1.9.10
├── @loopback/repository@1.15.2
├── @loopback/rest@1.21.0
├── @loopback/rest-explorer@1.4.2
├── @loopback/service-proxy@1.3.9
├── @loopback/testlab@1.9.2
├── @loopback/tslint-config@2.1.0
├── loopback-connector@4.9.0
├── loopback-connector-kv-redis@3.0.1
├── loopback-connector-postgresql@3.8.0
├── loopback4-authentication@2.1.3
├── loopback4-authorization@2.3.2
├── loopback4-soft-delete@1.2.0

**Comment by QuentinLB** [comment]
I use loopback 4 and I have the same problem with `numeric` fields. 

Here's an extract of my model : 
```ts
@model()
export class MyModel extends Entity {
   @property({
        type: 'number',
        required: true,
        postgresql: {
            dataType: 'decimal'
       }
  })
  my_prop: Number;
}
```
I tried to trace a `find()` call but I could find the point where the conversion is done.

**Comment by achrinza** [comment]
I suspect the following line may be the culprit:

https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/postgresql.js#L240-L272

As per [lb docs](https://loopback.io/doc/en/lb3/Implementing-create-retrieve-update-and-delete-methods.html#map-values-between-a-model-property-and-a-database-column), `fromColumnValue()` is responsible for converting from the database format to JavaScript. However, I'm not too familiar on how the function works to be sure.

**Comment by QuentinLB** [comment]
So I did some digging, turns out :

> [By default the PostgreSQL backend server returns everything as strings.](https://github.com/brianc/node-pg-types)

To fix this issue, you need to provide a parser for the targeted type. In my case I did the following :
```ts
import {types} from 'pg'

 // 1700 : Numeric (https://github.com/brianc/node-pg-types/blob/master/index.d.ts#L42)
types.setTypeParser(1700, parseFloat)
```

@vikramkh For your BigInt case, the fix should be `types.setTypeParser(20, BigInt)`. You must use node ^10.4.0, before this version Int were limited to 53 bits.

**Comment by QuentinLB** [comment]
As this issue is being closed, maybe the use of pg `setTypeParser` should be documented either in this repo or more importantly on loopback documentation as it's often the entry point for people using the connector. Just a suggestion.

**Comment by emonddr** [comment]
@QuentinLB , the solution you mention above seems to involve only node.js and the `pg` module. What about how it integrates with LB 3? If you could provide a minimal app that shows how you fully integrated your solution, it would help to document this properly. thx.

**Comment by QuentinLB** [comment]
Hi @emonddr 

I have no idea how it integrate with LB3, I stumbled on this issue while working on a LB4 server. What I can describe was my assumption working on my server that use this connector. Once my models defined I was surprised to see my non-string models properties being returned as string ([see my previous example](https://github.com/strongloop/loopback-connector-postgresql/issues/403#issuecomment-564455800)). 

As a way to avoid getting this type of issue open again I was suggesting to document the fact that neither LB nor this connector handle this behavior, allow the user facing this issue to setup their own `setTypeParser`.

Another way to manage this would be to setup those type parser in [initializeDataSource](https://github.com/strongloop/loopback-connector-postgresql/blob/1ce261b5f9f6ea8f4d80c35ad98543c582ca1a55/lib/postgresql.js#L30) but I'm not sure if it's the best place or the responsibility of the connector to do this.

Finally maybe it's the responsibility of [node-pg-types](https://github.com/brianc/node-pg-types) to change this behavior since it was added at a time Node didn't have proper 64bit numeric types. There's an issue open on their repo addressing this https://github.com/brianc/node-pg-types/issues/78

Hope that helps

**Comment by emonddr** [comment]
@QuentinLB , sorry, I meant LB4.

**Comment by QuentinLB** [comment]
[It's already documented](https://github.com/strongloop/loopback-connector-postgresql#numeric-data-type) :man_facepalming:

**Comment by vikramkh** [comment]
@QuentinLB , where exactly does this code go?
`
import {types} from 'pg'

 // 1700 : Numeric (https://github.com/brianc/node-pg-types/blob/master/index.d.ts#L42)
types.setTypeParser(1700, parseFloat)
`
 In the node_modules or in each of the individual repositories?

**Comment by QuentinLB** [comment]
@vikramkh 

It doesn't matter where you setup your types parsers since it's a static interface. What matter is when you do this setup. If you use Loopback, I recommend to do it during the application initialization ; this way you ensure that your parser are setup before any connection to the database and before migrations.

**Comment by vikramkh** [comment]
@QuentinLB  Thanks again for the help. After adding:
```
 types.setTypeParser(20, BigInt)
```
I get the error:
```
 500 SyntaxError: Cannot convert 0.00000 to a BigInt
    at Array.BigInt (<anonymous>)
    at Result.parseRow (/Users/vikramkhemlani/Desktop/loopback/meal-plan-loopback/node_modules/pg/lib/result.js:74:36)
    at Query.handleDataRow (/Users/vikramkhemlani/Desktop/loopback/meal-plan-loopback/node_modules/pg/lib/query.js:90:24)
    at Connection.<anonymous> (/Users/vikramkhemlani/Desktop/loopback/meal-plan-loopback/node_modules/pg/lib/client.js:279:22)
    at Connection.emit (events.js:189:13)
    at TLSSocket.<anonymous> (/Users/vikramkhemlani/Desktop/loopback/meal-plan-loopback/node_modules/pg/lib/connection.js:125:12)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```
I am using node v10.15.3

**Comment by QuentinLB** [comment]
You can't use `Json.stringify` to serialize BigInt (see the spec https://tc39.es/proposal-bigint/#sec-serializejsonproperty). One way to circumvent this is to provide your own `toJson` method :

```js
BigInt.prototype.toJSON = function() { return this.toString()  }
```
Taken from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#Use_within_JSON

However by my understanding of your issue, trying to serialize your data seems convoluted. By default node-pg return already everything as string, so if you try to serialize it afterwards no need to set a type parser. 

I think you should also look into the necessity to use BigInt, given the support for BigInt in js. If you use BigInt for an id, you should handle it as a string in you code since you won't use it as a number. Even better, use auto-generated uuids.
