### ISSUE TITLE
Impossible to exclude tables from migration

### ISSUE THREAD

**Issue by gioppoluca** [strongloop/loopback-connector-postgresql#447]
## Steps to reproduce

Execute migration on models that are only read only and on top of tables not managed by the project (but needed in the application)
If I execute a migration also these tables are taken into account

## Current Behavior

Try to migrate all the models

## Expected Behavior

Be able to exclude a model from the migration

**Comment by gioppoluca** [comment]
I saw that it is possible to add a list of models to the "app.migrateSchema" but it should be better and more generic to have an option in the model definition

**Comment by dhmlau** [comment]
Yes, it's possible to specify the model(s) that you want to run the database migration (also see code snippet in https://github.com/strongloop/loopback-next/issues/2831#issue-440068034). 

Having an option in the model definition to indicate this preference makes sense to me. It is probably related to the PR you submitted https://github.com/strongloop/loopback-connector-postgresql/pull/449. I'm thinking this should be implemented at an more abstract level rather than at the postgresql connector level itself. Let's continue the discussion on the PR.

**Comment by dhmlau** [comment]
PR #449
