### ISSUE TITLE
Connector attempts to connect to a database named after my Windows username

### ISSUE THREAD

**Issue by a-type** [strongloop/loopback-connector-postgresql#46]
Recently decided to give StrongLoop development a shot on my Windows machine. I understand that being NodeJS doesn't necessarily imply Windows support in reality, nor is Windows generally a high compatibility target. Still thought I'd drop a line here before perhaps switching back to Linux for development.

When I attempt to run a server, I get this output:

    Connection fails:  { [error: database "Grant" does not exist]
      name: 'error',
      length: 83,
      severity: 'FATAL',
      code: '3D000',
      detail: undefined,
      hint: undefined,
      position: undefined,
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      file: 'postinit.c',
      line: '775',
      routine: 'InitPostgres' }
    It will be retried for the next request.

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    error: database "Grant" does not exist
        at Connection.parseE (C:\Users\Grant\Documents\Git\current\node_modules\loopback-connector-postgresql\node_modules\pg\lib\connection.js:534:11)
        at Connection.parseMessage (C:\Users\Grant\Documents\Git\current\node_modules\loopback-connector-postgresql\node_modules\pg\lib\connection.js:361:17)
        at Socket.<anonymous> (C:\Users\Grant\Documents\Git\current\node_modules\loopback-connector-postgresql\node_modules\pg\lib\connection.js:105:22)
        at Socket.emit (events.js:95:17)
        at Socket.<anonymous> (_stream_readable.js:764:14)
        at Socket.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:426:10)
        at emitReadable (_stream_readable.js:422:5)
        at readableAddChunk (_stream_readable.js:165:9)
        at Socket.Readable.push (_stream_readable.js:127:10)

My name is Grant, as is my username on this Windows box. To test further, I cloned the project on another machine where my username is a-type, and sure enough, the connector tries to reach a database named `a-type`.

I am pretty confident my `datasources.json` is correct. Here's a redacted version:

    {
      "db": {
        "name": "db",
        "connector": "memory"
      },
      "CurrentDB": {
        "host": "<db-endpoint>.us-east-1.rds.amazonaws.com",
        "port": 5432,
        "username": "postgres",
        "password": "<db-password>",
        "name": "CurrentDB",
        "connector": "loopback-connector-postgresql"
     }
    }

Having some trouble tracking this down, and I haven't seen anyone else mention it. Kind of hoping someone spots something off in my config, but it could be an underlying compatibility issue with Windows.

**Comment by raymondfeng** [comment]
You need to add the "database" property to your configuration.

**Comment by rex** [comment]
Found this issue and felt compelled to comment. I am having the same issue as @a-type but I **do** have the `database` property defined. It doesn't appear to be reading the configuration at all, honestly, because any changes I make to the object in `dataSources.json` *are not* reflected in the connection attempts. Which is doubly odd because I'm introspecting the `app.dataSources` object to ensure that my parameters are making it through to the PG connection constructor. They are making it through in the `settings` property but the connections are still failing.

This was working yesterday, and I'm not entirely sure why it's failing all of a sudden now.

**Comment by raymondfeng** [comment]
Can you try to dump out debug information as follows?
```sh
SET DEBUG=loopback:connector:postgresql
node .
```

**Comment by rex** [comment]
Sure thing @raymondfeng! I'll post back shortly.

BTW: Holy wow that was a fast response. You rock.

**Comment by rex** [comment]
Alright. I actually resolved the issue in a different way than anticipated, and it is not the fault of `loopback-connector-postgresql`.

I am in the middle of attempting to migrate our team's data from MySQL to PostgreSQL. In `dataSources.json` I had created multiple sources. One MySQL source for the legacy database, one PostgreSQL source for the local PG instance I was using to test with, and one PostgreSQL source that will be in the application infrastructure. Turns out that Strongloop doesn't play nicely with multiple data sources that use the same connector, and it was silently failing because even though I told it to use a specific data source it was using the last data source that had the `postgresql` connector defined.

Which is annoying and undocumented (to my knowledge) but ultimately fixable :)

**Comment by 0candy** [comment]
@a-type Can you confirm whether your issue was resolved with Raymond's solution?

**Comment by a-type** [comment]
@0candy apologies for not following up. It was resolved by Raymond's solution to my recollection, but it's been a while.

**Comment by 0candy** [comment]
@a-type Thank you! Closing this issue.

**Comment by GlareGlimmering** [comment]
PostgreSQL 默认将未加引号的标识符（例如数据库名或表名）转换为小写。你的数据库名为Grant，但是再次连接时是grant，所以报错。
这个问题困扰了我一下午，希望对后来者有帮助😊。
