### ISSUE TITLE
Return isNewInstance from upsert

### ISSUE THREAD

**Issue by flintinatux** [strongloop/loopback-connector-postgresql#91]
Would like to have support for `ctx.isNewInstance` in "after save" operation hooks, similar to the fix done for the MySQL connector: https://github.com/strongloop/loopback-connector-mysql/pull/91.

Documentation on this feature is here: http://docs.strongloop.com/display/public/LB/Operation+hooks#Operationhooks-Checkingforsupportofctx.isNewInstance

**Comment by tamilvendhank** [comment]
+1

**Comment by enceladus** [comment]
+1

**Comment by ssh24** [comment]
Adding it as a feature request. Currently, calling `updateOrCreate()` with a model attached to a postgresql connector runs the Juggler's [`updateOrCreate()`](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L474).

This is because postgresql's [`updateOrCreate()`](https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/postgresql.js#L245) is commented out.

To enable this feature, we need to bring back the code on postgresql and apply a similar fix to that of [mysql](https://github.com/strongloop/loopback-connector-mysql/pull/91).

**Comment by jonathanRinciari** [comment]
Are there plans to continue supporting postgres? Or is postgres considered unsupported now, and we shouldnt expect this to be implemented?

**Comment by virkt25** [comment]
@jonathanRinciari Would you be interested in creating a PR to add this feature to the postgres connector? We still support the connector but work on new features is limited at the moment as we focus on loopback-next
